project:
  name: customer-api
  type: backend-api
  language: java
  framework: spring-boot

repository:
  type: git
  # url: https://github.com/ThingsWithPings/simple-crud-springboot-project #crud simple que aplica ciertos criterios para su arquitectura, con fallas.
  # url: https://github.com/Saurabh-pec/Calculator-javaProject # proyecto spaggeti falla con 0
  url: https://github.com/SvenWoltmann/hexagonal-architecture-java # proyecto con arquitectura hexagonal
  # url: https://github.com/Azure-Samples/java-on-azure-examples # ejemplo con azure
  # url: /temp_repo_clonado
  branch: main
